config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

	resources :projects do
    resources :issues
    member do
      post :add_resource
      post :user_unassign
    end
  end

  get '/assign_bug', to: 'issues#assign_bug'
  get '/unassign_bug', to: 'issues#unassign_bug'

  root to: 'static_pages#home'

end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :project
  belongs_to :user

  mount_uploader :img, ImageUploader

  validates :title, presence: true, uniqueness: true
  
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	
	before_action :authenticate_user!

	before_action :set_project, only: [:index, :new, :create]

	before_action :set_issue, only: [:edit, :update, :show, :assign_bug, :unassign_bug]

	def index
		@issues = @project.issues.paginate(page: params[:page])
		@user = User.find(current_user.id)
	end

	def new
		@issue = Issue.new
		authorize @issue
	end

	def create
		@issue = current_user.issues.new(issue_params)
		@issue.project_id = @project.id
		authorize @issue
	 
	 	if @issue.save
	 		flash[:notice] = "Reported!"
	 		redirect_to project_issues_path
	 	else
	 		render 'new'
	 	end
	end

	def edit
	end

	def update
		if @issue.update_attribute(:status, params[:issue][:status])
			flash[:notice] = "status updated!"
			redirect_to edit_project_issue_path
		else
			flash[:alert] = "Failed!"
			redirect_to edit_project_issue_path
		end
	end

	def show
	end

	def assign_bug
		@project = Project.find(@issue.project_id)
		
		if @issue.d_id
			flash[:alert] = "Already assigned to someone!"
			redirect_to project_issue_path(@project.id, @issue.id)
		else
			@issue.update_attribute(:d_id, current_user.id)
			flash[:notice] = "Assigned!"
			redirect_to project_issues_path(@project.id)
		end
	end

	def unassign_bug
		@project = Project.find(@issue.project_id)

		if @issue.d_id
			@issue.update_attribute(:d_id, nil)
			flash[:notice] = "Unassigned!"
			redirect_to project_issues_path(@project.id)
		else
			flash[:alert] = "Already Unassigned!"
			redirect_to project_issue_path(@project.id, @issue.id)	
		end
	end

	private
		def issue_params
			params.require(:issue).permit(:title, :description, :deadline, :issue_type, :status, :img)
		end

		def set_project
			@project = Project.find(params[:project_id])
		end

		def set_issue
			@issue = Issue.find(params[:id])
		end
end

app/helpers/issues_helper.rb
module IssuesHelper
  SELECTOR = ['Bug', 'Feature']
  TYPES = ['New', 'Started', 'Resolved']
  
  def select_options
    TYPES.map{|type| [type, type]}
  end
  def selector
    SELECTOR.map{|selector| [selector, selector]}
  end
end

app/views/issues/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<table class="table">
			<thead class="thead-dark">
			 	<tr>
				    <th>Issue Name</th>
				    <th>Issue Description</th>
				    <th>Issue Type</th>
				    <th>Issue Status</th>
				    <th>Reported</th>
				    <th>Change Status</th>
				</tr>
			</thead>
			<tr>
				<td><%= @issue.title %></td>
				<td><%= @issue.description %></td>
				<td><%= @issue.issue_type %></td>
				<td><%= @issue.status %></td>
				<td><%= time_ago_in_words(@issue.created_at) %> ago.</td>
				<%= form_for(@issue, url: project_issue_path, method: 'patch') do |f| %>

					<% if @issue.issue_type == "Feature" %> 
						<td>
	    				<%= f.select :status, options_for_select([["Started", "Started"], ["Completed", "Completed"]],  class: 'form-control' ) %>
	    				<%= f.submit "Update Status", class: "btn btn-primary" %></td>
    				<% elsif @issue.issue_type == "Bug"%>
	    				<td>
	    				<%= f.select :status, options_for_select([["Started", "Started"], ["Resolved", "Resolved"]],  class: 'form-control' ) %>
	    				<%= f.submit "Update Status", class: "btn btn-primary" %></td>

    				<% end %>
    			<% end %>
    		</tr>
    	</table>
    	<% if @issue.img? %>
		<li>
			<%= image_tag @issue.img.url %>
		</li>
		<% end %>
	</div>
</div>

<%= link_to "Back", :back %>

app/views/issues/index.html.erb
<% if policy(Issue).new? %>
	<%= link_to "Report New One", new_project_issue_path(@project.id), class: "btn btn-primary" %>
<% end %>
<h1><%= @project.name %></h1>

<% if !@issues %>
	<h2>No Issues.</h2>

<% else %>
	<h2>All Issues</h2>

	<%= will_paginate %>	
	
	<ul class="issues">
		<table class="table">

		 	<thead class="thead-dark">
			 	<tr>
				    <th>Issue Name</th>
				    <th>Issue Description</th>
				    <th>Issue Type</th>
				    <th>Issue Status</th>
						<% @issues.each do |issue| %>
							<% if policy(issue).edit? %>
							<th></th>
			    		<% end %>
						<% end %>
		  		</tr>
			</thead>
			
			
			<% @issues.each do |issue| %>
			<tr>
				<td><%= link_to issue.title, project_issue_path(issue.project_id, issue.id) %></td>
				<td><%= issue.description %></td>
				<td><%= issue.issue_type %></td>
				<td><%= issue.status %></td>

				<% if policy(issue).edit? %>
					<td><%= link_to "edit status", edit_project_issue_path(issue.project_id, issue.id) %></td>
				<% end %>
			</tr>
			<% end %>
					
		</table>
	</ul>

	<%= will_paginate %>

<% end %>

<%= link_to "Back", :back %>

app/views/issues/new.html.erb
<h1>Report Here!</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@issue, url: project_issues_path) do |f| %>

			<%= render 'shared/error_message', object: f.object %>
			
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
			
			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>

			<%= f.label :deadline %>
			<%= f.text_field :deadline, class: 'form-control' %>


 			<%= f.label :issue_type %>
		    <%= f.select(:issue_type, selector, {}, {class: "form-control" }) %>
    
			<%= f.label :status %>
    	<%= f.select(:status, select_options, {}, {class: "form-control feature-selecter" }) %>			
    
    	<%= f.file_field :img %>
		
			<%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

<%= link_to "Back", :back %>

<%= javascript_include_tag "custom" %>



<% if false %>
  <%= select_tag :status_bug, options_for_select([["New", "New"], ["Started", "Started"], ["Resolved", "Resolved"]]), class: "form-control bug-selecter"  %>
<% end %>

app/views/issues/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
		<table class="table">
			<thead class="thead-dark">
			 	<tr>
				    <th>Issue Name</th>
				    <th>Issue Description</th>
				    <th>Issue Type</th>
				    <th>Issue Status</th>
				    <th>Reported</th>
				</tr>
			</thead>
			<tr>
				<td><%= @issue.title %></td>
				<td><%= @issue.description %></td>
				<td><%= @issue.issue_type %></td>
				<td><%= @issue.status %></td>
				<td><%= time_ago_in_words(@issue.created_at) %> ago.</td>

					<% if policy(Issue).show? %>
						<div class="row">
							<div class="col-md-6 col-md-offset-3">
								<% if policy(@issue).not_assigned? %>
									<td><%= link_to "Assign youself?", assign_bug_path(id: @issue.id), class: "btn btn-primary" %></td>
								<% else %>
									<td><%= link_to "Unassign youself?", unassign_bug_path(id: @issue.id), class: "btn btn-primary" %></td>
								<% end %>

							</div>
						</div>
					<% end %>
				</tr>
			</table>
		</div>
		<div class="col-md-6">
			<% if @issue.img? %>
				<%= image_tag @issue.img.url %>
			<% end %>
		</div>
	</div>
</div>

<%= link_to "Back", :back %>