config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

	resources :projects do
    resources :issues
    member do
      post :add_resource
      post :user_unassign
    end
  end

  get '/assign_bug', to: 'issues#assign_bug'
  get '/unassign_bug', to: 'issues#unassign_bug'

  root to: 'static_pages#home'

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :u_relationships, class_name: "Relationship", foreign_key: "project_id", dependent: :destroy
 
  has_many :users, through: :u_relationships, source: :user

  has_many :issues, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	before_action :authenticate_user!

	before_action :set_project, only: [:show, :create, :edit, :update, :destroy, :add_resource, :user_unassign]

	def index
		if current_user.Manager?
			@projects = current_user.projects.paginate(page: params[:page])
		else
			@projects = current_user.user_projects.paginate(page: params[:page])
		end
	end

	def new
		@project = Project.new
		authorize @project
	end

	def create
  	authorize @project

  	if @project.save
  		flash[:notice] = "Your project has been created!"
  		redirect_to projects_path
  	else
  		render 'new'
  	end
	end

	def edit
		authorize @project
	end

	def update
		authorize @project

		if @project.update(project_params)
			redirect_to projects_path
		else
			flash[:alert] = "Updation Failed!"
			render 'edit'
		end
	end

	def show
		@users = @project.users.where.not(user_type: "Manager")
	end

	def destroy
		authorize @project

		@project.destroy
		flash[:notice] = "Project deleted"
		redirect_to projects_path
	end

	def user_unassign
		@relation = Relationship.where(project_id: @project.id, user_id: params[:user_id]).first

		authorize @project

		@relation.destroy
		flash[:notice] = "Unassigned!"

		redirect_to project_path(@project)
	end

	def add_resource
		authorize @project
		@user = User.find_by(email: params[:email])
		
		if @user
			if @user.Dev? or @user.QA?
			 	@relationship = Relationship.new(project_id: @project.id, user_id: @user.id)
				if @relationship.save
					flash[:notice] = "Your project has been assigned!"
					redirect_to project_path(@project)
				else
					flash[:alert] = "Already Assigned to this project!"
					redirect_to project_path(@project)
				end
			else
				flash[:alert] = "Developer/QA does not exist!"
				redirect_to project_path(@project)
			end
		else
			flash[:alert] = "User does not exist!"
			redirect_to project_path(@project)
		end
	end

	private
  	def project_params
  		params.require(:project).permit(:name, :description)
  	end

  	def set_project
			@project = Project.find(params[:id])
  	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%= form_for(@project) do |f| %>

  <%= render 'shared/error_message', object: f.object %>

  <div class="field">
	  <%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="field">
	  <%= f.label :description %>
		<%= f.text_field :description, class: 'form-control' %>
	</div>

  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-primary'%>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/projects/index.html.erb
<% if policy(Project).new? %>
	<%= link_to "Create New Project", new_project_path, class: "btn btn-primary" %>
<% end %>

<% if !@projects %>
	<h3>No Proejcts Currently Assigned.</h3>

<% else %>
	<h1>All Projects</h1>

	<%= will_paginate %>
	
	<ul class="project">
		<table class="table">
		 	<thead class="thead-dark">
			 	<tr>
				    <th>Project Name</th>
				    <th>Project Description</th>
				    <% if policy(Project).edit? %>
			    		<th></th>
			    		<th></th>
						<% elsif policy(Project).bugs?%>
							<th></th>
			    	<% end %>
		  		</tr>
			</thead>
			<% @projects.each do |project| %>
			<tr>
			  <td><%= link_to project.name, project %></td>
			  <td><%= project.description %></td>
						  
				<% if policy(Project).edit? %>
				 <td><%= link_to "edit", edit_project_path(project) %></td>
				 <td><%= link_to "delete", project, method: :delete, data: { confirm: "You sure?" } %></td>
				<% elsif policy(Project).bugs?%>
					<td><%= link_to "Project Issues", project_issues_path(project.id) %></td>
				<% end %>
			</tr>
			<% end %>
		</table>
	</ul>

	<%= will_paginate %>

<% end %>

<%= link_to "Back", :back %>

app/views/projects/new.html.erb
<h1>Create New Project</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@project) do |f| %>

			<%= render 'shared/error_message', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			
			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>


			
			
			<%= f.submit "Create Project", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

<%= link_to "Back", :back %>

app/views/projects/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h2>Assigned Employees to the Project</h2>

			<ul class="user">
				<table class="table">
				 	<thead class="thead-dark">
					 	<tr>
					    <th>Name</th>
					    <th>Email</th>
					    <th>Department</th>
					    <% if policy(Project).user_unassign? %>
					    <th></th>
					    <% end %>
					  </tr>
					</thead>
  				<% @users.each do |user| %>
						<tr>
						  <td><%= user.name %></td>
						  <td> <%= user.email %></td>
						  <td> <%= user.user_type %></td>
						  
						  <% if policy(Project).user_unassign? %>
						  <td>
						    <%= link_to "Unassign", user_unassign_project_path(user_id: user.id), method: "post", data: { confirm: "You sure?" } %></td>
						  <% end %>
						</tr>
					<% end %>
				</table>
				


			</ul>
		</div>
		<div class="col-md-6">

			<% if policy(Project).bugs? %>

			<h2><%= link_to "Project Issues", project_issues_path(@project.id) %></h2>

			<% end %>

			<% if policy(Project).add_resource? %>
				<h2>Assign Developer/QA to Project</h2>
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<%= form_tag(add_resource_project_path, method: 'post', id: 'search-form') do %>

							<div class="field">
							    <%= label_tag :email %><br />
							    <%= email_field_tag :email %>
							</div>

							<%= submit_tag "Add", class: "btn btn-primary" %>
						<% end %>
					</div>
				</div>
			<% end %>

		</div>
	</div>
</div>

<%= link_to "Back", :back %>

<% if false %>
			<% if policy(Project).assign_resource? %>
				<h2>Assign QA to Project</h2>
				<div class="row">
					<div class="col-md-6 col-md-offset-3">
						<%= form_tag(assign_resource_path(project_id: @project.id), method: 'post', id: 'search-form') do %>

							<div class="field">
							    <%= label_tag :email %><br />
							    <%= email_field_tag :email%>
							</div>

							<%= submit_tag "Add", class: "btn btn-primary" %>
						<% end %>
					</div>
				</div>
			<% end %>
<% end %>