config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions' }

	resources :projects do
    resources :issues
    member do
      post :add_resource
      post :user_unassign
    end
  end

  get '/assign_bug', to: 'issues#assign_bug'
  get '/unassign_bug', to: 'issues#unassign_bug'

  root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="http://localhost:3000/">Bugzilla</a>
		by <a href="http://www.facebook.com/ihashirkhan">Hashir Rehman Khan</a>
	</small>

	<nav>
		<ul>
			<small><span class="footer_text">Copyright © 2018. All Rights Reserved.</span></small>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "bugzilla", root_path, id: "logo" %>

		<nav>
			<ul class="nav navbar-nav navbar-right .nav-area">
				<li><%= link_to "Home", root_path %></li>
				

				<% if user_signed_in? %>
					<li ><%= link_to "Projects", projects_path %></li>
					
					<li ><%= link_to current_user.name, edit_user_registration_path %></li>
					<li ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
							
				<% else %>
					<li><%= link_to "Log in", new_user_session_path %></li>
				<% end %>

			</ul>
		</nav>
	</div>
</header>

<%= javascript_include_tag "custom" %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
		
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>